pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Fit&Flow"
include ':app'
include ':ui-layer'
include ':domain-layer'
include ':data-layer'
include ':data:common-data'
include ':data:categories-data'
include ':data:exercises-data'
include ':data:trainings-data'
include ':data:user-data'
